blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogPostCreateView, BlogPostListView, BlogPostDetailView, BlogPostUpdateView, BlogPostDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogPostCreateView.as_view(), name='create'),
    path('', BlogPostListView.as_view(), name='list'),
    path('view/<int:pk>/', cache_page(60)(BlogPostDetailView.as_view()), name='view'),
    path('edit/<int:pk>/', BlogPostUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', BlogPostDeleteView.as_view(), name='delete')
]

mailing/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mailing.apps import MailingConfig
from mailing.views import MailingMessageListView, MailingMessageCreateView, MailingMessageDetailView, \
    MailingMessageUpdateView, MailingMessageDeleteView, MailingSettingsCreateView, MailingSettingsUpdateView, \
    MailingSettingsListView, MailingSettingsDetailView, MailingSettingsDeleteView, MailingStatusListView, \
    MailingStatusDeleteView, HomePageView

app_name = MailingConfig.name

urlpatterns = [
    path('', MailingMessageListView.as_view(), name='list'),
    path('create/', MailingMessageCreateView.as_view(), name='create'),
    path('<int:pk>/', MailingMessageDetailView.as_view(), name='view'),
    path('<int:pk>/update/', MailingMessageUpdateView.as_view(), name='edit'),
    path('<int:pk>/delete/', MailingMessageDeleteView.as_view(), name='delete'),
    path('settings/', MailingSettingsListView.as_view(), name='settings_list'),
    path('settings/create/', MailingSettingsCreateView.as_view(), name='settings_create'),
    path('settings/<int:pk>/', MailingSettingsDetailView.as_view(), name='settings_view'),
    path('settings/<int:pk>/update/', MailingSettingsUpdateView.as_view(), name='settings_edit'),
    path('settings/<int:pk>/delete/', MailingSettingsDeleteView.as_view(), name='settings_delete'),
    path('status/', MailingStatusListView.as_view(), name='status_list'),
    path('status/<int:pk>/delete/', MailingStatusDeleteView.as_view(), name='status_delete'),
    path('home_page/', cache_page(120)(HomePageView.as_view(template_name='mailing/home_page.html')), name='home_page'),
]

mailing_list_service/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('recipients/', include('recipients.urls', namespace='recipients')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/models.py
from django.db import models

from recipients.models import Recipients
from users.models import User

FREQUENCY_CHOICES = [('daily', 'раз в день'), ('weekly', 'раз в неделю'), ('monthly', 'раз в месяц'), ]
STATUS_OF_NEWSLETTER = [("Create", 'Создана'), ("Started", 'Отправляется'), ("Done", 'Завершена'), ("Cancel", 'Отменена'), ]


class MailingMessage(models.Model):
    """Модель сообщения"""
    title = models.CharField(max_length=150, verbose_name='title')
    content = models.TextField(verbose_name='content')
    creator = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='creator', null=True, blank=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'


class MailingSettings(models.Model):
    """Модель настроек отправки"""
    first_datetime = models.DateTimeField(verbose_name='first_datetime')
    next_datetime = models.DateTimeField(verbose_name='next_datetime', null=True, blank=True)
    end_time = models.DateTimeField(verbose_name='end_time')
    sending_period = models.CharField(max_length=50, verbose_name='sending_period', choices=FREQUENCY_CHOICES)
    message = models.ForeignKey(MailingMessage, on_delete=models.CASCADE, verbose_name='message')
    creator = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='creator', null=True, blank=True)
    settings_status = models.CharField(max_length=50, verbose_name='settings_status', choices=STATUS_OF_NEWSLETTER, default='Create')
    recipients = models.ManyToManyField(Recipients, verbose_name='recipients')

    def __str__(self):
        return f'{self.message} отправляется каждый {self.sending_period} с {self.first_datetime} для {self.recipients}'

    class Meta:
        verbose_name = 'Настройка отправки'
        verbose_name_plural = 'Настройки отправки'
        permissions = [
            ('can_see_mailing_settings', 'can see all mailing settings'),
            ('can_change_settings_status', 'can change settings status')
        ]


class MailingStatus(models.Model):
    """Модель статуса отправки"""
    last_datetime = models.DateTimeField(auto_now_add=True, verbose_name='last_datetime')
    status = models.CharField(max_length=50, verbose_name='статус попытки')
    mailing_response = models.TextField(verbose_name='mailing_response')
    mailing_id = models.ForeignKey(MailingSettings, on_delete=models.CASCADE, verbose_name='mailing_id', null=True, blank=True)

    def __str__(self):
        return f'{self.status} отправлялось {self.last_datetime}, ответ сервера: {self.mailing_response}'

    class Meta:
        verbose_name = 'Статус отправки'
        verbose_name_plural = 'Статусы отправки'

mailing/forms.py
from django import forms
from django.forms import BooleanField

from mailing.models import MailingMessage, MailingSettings


class StyleFormMixin:
    """Стилизация форм"""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'


class MailingMessageForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = MailingMessage
        exclude = ['creator']


class MailingSettingsForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = MailingSettings
        exclude = ['next_datetime', 'settings_status', 'creator']


class MailingSettingsModeratorForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = MailingSettings
        fields = ('settings_status', )

mailing/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, DeleteView, ListView, DetailView

from mailing.forms import MailingMessageForm, MailingSettingsForm, MailingSettingsModeratorForm
from mailing.models import MailingMessage, MailingSettings, MailingStatus
from mailing.services import get_three_random_blog


class MailingMessageCreateView(CreateView, LoginRequiredMixin):
    model = MailingMessage
    form_class = MailingMessageForm
    success_url = reverse_lazy('mailing:list')

    def form_valid(self, form):
        """Сохранение создателя сообщения"""
        mailing_message = form.save()
        user = self.request.user
        mailing_message.creator = user
        mailing_message.save()
        return super().form_valid(form)


class MailingMessageUpdateView(UpdateView):
    model = MailingMessage
    form_class = MailingMessageForm
    success_url = reverse_lazy('mailing:list')


class MailingMessageDeleteView(DeleteView):
    model = MailingMessage
    success_url = reverse_lazy('mailing:list')


class MailingMessageListView(ListView):
    model = MailingMessage


class MailingMessageDetailView(DetailView):
    model = MailingMessage


class MailingSettingsCreateView(CreateView):
    model = MailingSettings
    form_class = MailingSettingsForm
    success_url = reverse_lazy('mailing:settings_list')

    def form_valid(self, form):
        """Сохранение создателя сообщения"""
        mailing_settings = form.save()
        user = self.request.user
        mailing_settings.creator = user
        mailing_settings.save()
        return super().form_valid(form)


class MailingSettingsUpdateView(LoginRequiredMixin, UpdateView):
    model = MailingSettings
    form_class = MailingSettingsForm
    success_url = reverse_lazy('mailing:settings_list')

    def get_form_class(self):
        """Переопределяем форму для модератора"""
        user = self.request.user
        if user == self.object.creator:
            return MailingSettingsForm
        if user.has_perm('mailing.can_change_settings_status'):
            return MailingSettingsModeratorForm
        raise PermissionDenied


class MailingSettingsListView(ListView):
    model = MailingSettings


class MailingSettingsDetailView(DetailView):
    model = MailingSettings


class MailingSettingsDeleteView(DeleteView):
    model = MailingSettings
    success_url = reverse_lazy('mailing:settings_list')


class MailingStatusListView(ListView):
    model = MailingStatus


class MailingStatusDeleteView(DeleteView):
    model = MailingStatus
    success_url = reverse_lazy('mailing:status_list')


class HomePageView(ListView):
    model = MailingSettings

    def get_context_data(self, **kwargs):
        """Получаем необходимые данные для домашней страницы"""
        context = super().get_context_data(**kwargs)
        queryset = self.get_queryset()
        mailing_settings = queryset.filter()

        mailing_settings_count = mailing_settings.count()
        mailing_settings_active_count = mailing_settings.filter(settings_status='Started').count()
        recipients_count = mailing_settings.values('recipients').distinct().count()

        context['mailing_settings_count'] = mailing_settings_count
        context['mailing_settings_active_count'] = mailing_settings_active_count
        context['recipients_count'] = recipients_count
        context['blog_posts'] = get_three_random_blog(self.request)

        return context

mailing/templates/mailing/base.html
{% load static %}
<!doctype html>
<html lang="ru" data-bs-theme="auto">
    <head>
        <meta charset="utf-8">
        <title>Управление рассылками</title>

        <!-- Bootstrap core CSS -->
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="container py-3">
        {% include 'mailing/includes/inc_menu.html' %}

        {% block content %}
        {% endblock %}

        <footer class="pt-4 my-md-5 pt-md-5 border-top">
            <div class="row">
                  <div class="col-12 col-md">
                        <small class="d-block mb-3 text-body-secondary">&copy; 2024</small>
                  </div>
            </div>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    </body>
</html>

mailing/templates/mailing/home_page.html
{% extends 'mailing/base.html' %}
{% load my_tags %}
{% block content %}

     <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
        <h1 class="display-4 fw-normal text-body-emphasis">Сервис email рассылок</h1>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="card mb-3">
                    <div class="card-header bg-primary text-white">
                        <h4 class="my-0 font-weight-normal">О нас</h4>
                    </div>
                    <div class="card-body">
                        <ul class="list-unstyled mt-3 mb-4">
                            <li>Всего зарегистрировано рассылок: {{ mailing_settings_count }}</li>
                            <li>Из них активно на данный момент: {{ mailing_settings_active_count }}</li>
                            <li>Общее количество доступных получаетелей: {{ recipients_count }}</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            {% for post in blog_posts %}
                <div class="col-md-4 mb-4">
                    <div class="card h-100">
                        <div class="card-header bg-primary text-white">
                            <h4 class="my-0 font-weight-bold">{{ post.title }}</h4>
                        </div>
                        <div class="card-body">
                            {% if post.image %}
                                <img src="{{ post.image | media_filter }}" class="rounded mx-auto d-block w-100">
                            {% endif %}
                            <p class="card-text mt-3">{{ post.content | slice:":100" }}</p>
                        </div>
                        <div class="card-footer bg-transparent border-0">
                            <p class="card-text">Просмотров: {{ post.views_count }}</p>
                            <a class="btn btn-primary" href="{% url 'blog:view' post.pk %}" role="button">Просмотреть</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

mailing/templates/mailing/mailingmessage_confirm_delete.html
{% extends 'mailing/base.html' %}
{% block content %}
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <p>Хотите удалить рассылку {{ object.title }}?</p>
                        <button type="submit" class="btn btn-success">Удалить</button>
                        <a class="btn btn-primary" href="{% url 'mailing:list' %}" role="button">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

mailing/templates/mailing/mailingmessage_detail.html
{% extends 'mailing/base.html' %}
{% block content %}
    <div class="container">
        <div class="row text-center">
            <div class="col-9">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">{{ object.title }}</h4>
                    </div>
                    <div class="card-body">
                        <h5>{{ object.content }}</h5>
                        <p>{{ object.recipients }}</p>
                        {% if user == object.creator %}
                            <a class="btn btn-primary" href="{% url 'mailing:edit' object.pk %}" role="button">Изменить</a>
                            <a class="btn btn-primary" href="{% url 'mailing:delete' object.pk %}" role="button">Удалить</a>
                        {% endif %}
                        <a class="btn btn-primary" href="{% url 'mailing:list' %}" role="button">Назад</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

mailing/templates/mailing/mailingmessage_form.html
{% extends 'mailing/base.html' %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col">
                <form class="row" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="card">
                        <div class="card-body">
                            {{ form.as_p }}
                        </div>
                        <button type="submit" class="btn btn-primary mt-3">
                            {% if object %}
                                Изменить рассылку
                            {% else %}
                                Добавить рассылку
                            {% endif %}
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

mailing/templates/mailing/mailingmessage_list.html
{% extends 'mailing/base.html' %}

{% block content %}
    <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
        <h1 class="display-4 fw-normal text-body-emphasis">Все рассылки</h1>
        {% if user.is_authenticated %}
            <h3>
                <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="{% url 'mailing:create' %}">Создать рассылку</a>
            </h3>
        {% endif %}
    </div>
    <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
        {% for mail in object_list %}
            <div class="col">
                <div class="card mb-4 rounded-3 shadow-sm">
                    <div class="card-header py-3">
                        <h2 class="my-0 fw-normal">{{ mail.title }}</h2>
                    </div>
                    <div class="card-body">
                        <p class="card-title pricing-card-title">{{ mail.content | slice:":100" }}</p>
                        <a class="btn btn-primary" href="{% url 'mailing:view' mail.pk %}" role="button">Просмотреть</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

mailing/templates/mailing/mailingsettings_confirm_delete.html
{% extends 'mailing/base.html' %}
{% block content %}
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <p>Хотите удалить рассылку от {{ object.first_datetime }}?</p>
                        <button type="submit" class="btn btn-success">Удалить</button>
                        <a class="btn btn-primary" href="{% url 'mailing:settings_list' %}" role="button">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

mailing/templates/mailing/mailingsettings_detail.html
{% extends 'mailing/base.html' %}
{% block content %}
    <div class="container">
        <div class="row text-center">
            <div class="col-9">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">{{ object.message.title }}</h4>
                    </div>
                    <div class="card-body">
                        <h5>{{ object.message.content }}</h5>
                        <h5>От {{ object.first_datetime }}</h5>
                        {% for recipient in object.recipients.all %}
                            <p class="card-title pricing-card-title">Для: {{ recipient }}</p>
                        {% endfor %}
                        {% if perms.mailing.can_change_settings_status or user == object.creator %}
                            <a class="btn btn-primary" href="{% url 'mailing:settings_edit' object.pk %}" role="button">Изменить</a>
                        {% endif %}
                        {% if user == object.creator %}
                            <a class="btn btn-primary" href="{% url 'mailing:settings_delete' object.pk %}" role="button">Удалить</a>
                        {% endif %}
                        <a class="btn btn-primary" href="{% url 'mailing:settings_list' %}" role="button">Назад</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

mailing/templates/mailing/mailingsettings_form.html
{% extends 'mailing/base.html' %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col">
                <form class="row" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="card">
                        <div class="card-body">
                            {{ form.as_p }}
                        </div>
                        <button type="submit" class="btn btn-primary mt-3">
                            {% if object %}
                                Изменить настройки рассылки
                            {% else %}
                                Добавить рассылку
                            {% endif %}
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

mailing/templates/mailing/mailingsettings_list.html
{% extends 'mailing/base.html' %}
{% block content %}

     <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
        <h1 class="display-4 fw-normal text-body-emphasis">Запланированные рассылки</h1>
         {% if user.is_authenticated %}
            <h3>
                <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="{% url 'mailing:settings_create' %}">Запланировать рассылку</a>
            </h3>
         {% endif %}
    </div>
    <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
        {% for setting in object_list %}
            <div class="col">
                <div class="card mb-4 rounded-3 shadow-sm">
                    <div class="card-header py-3">
                        <h2 class="my-0 fw-normal">Начало рассылки: {{ setting.first_datetime }}</h2>
                    </div>
                    <div class="card-body">
                        {% for recipient in setting.recipients.all %}
                            <p class="card-title pricing-card-title">Для: {{ recipient }}</p>
                        {% endfor %}
                        <p class="card-title pricing-card-title">Периодичность: {{ setting.sending_period }}</p>
                        <p class="card-title pricing-card-title">Завершится: {{ setting.end_time }}</p>
                        <p class="card-title pricing-card-title">Статус: {{ setting.settings_status }}</p>
                        <p class="card-title pricing-card-title">Сообщение: {{ setting.message }}</p>
                        {% if perms.mailing.can_see_mailing_settings or user == setting.creator %}
                            <a class="btn btn-primary" href="{% url 'mailing:settings_view' setting.pk %}" role="button">Просмотреть</a>
                        {% endif %}
                  </div>
              </div>
            </div>
        {% endfor %}
    </div>

{% endblock %}

mailing/templates/mailing/mailingstatus_confirm_delete.html
{% extends 'mailing/base.html' %}
{% block content %}
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <p>Хотите удалить статус рассылки {{ object.mailing_id.message }}?</p>
                        <button type="submit" class="btn btn-success">Удалить</button>
                        <a class="btn btn-primary" href="{% url 'mailing:status_list' %}" role="button">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

mailing/templates/mailing/mailingstatus_list.html
{% extends 'mailing/base.html' %}
{% block content %}

    <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
        <h1 class="display-4 fw-normal text-body-emphasis">Статусы рассылок</h1>
    </div>
    <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
        {% for mailing in object_list %}
            <div class="col">
                <div class="card mb-4 rounded-3 shadow-sm">
                    <div class="card-header py-3">
                        <h2 class="my-0 fw-normal">Рассылка: {{ mailing.mailing_id.message }}</h2>
                        <h4 class="my-0 fw-normal">Статус рассылки: {{ mailing.mailing_id.settings_status }}</h4>
                    </div>
                    <div class="card-body">
                        <p class="card-title pricing-card-title">В статусе: {{ mailing.status }} </p>
                        <p class="card-title pricing-card-title">Последняя отправка: {{ mailing.last_datetime }}</p>
                        <p class="card-title pricing-card-title">С ответом: {{ mailing.mailing_response }}</p>
                        {% if mailing.mailing_id.settings_status == 'Done' %}
                        <p class="card-title pricing-card-title">Рассылка завершена</p>
                        {% else %}
                        <p class="card-title pricing-card-title">Дата следующей отправки: {{ mailing.mailing_id.next_datetime }}</p>
                        {% endif %}
                        <a class="btn btn-primary" href="{% url 'mailing:status_delete' mailing.pk %}" role="button">Удалить</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}