blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogPostCreateView, BlogPostListView, BlogPostDetailView, BlogPostUpdateView, BlogPostDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogPostCreateView.as_view(), name='create'),
    path('', BlogPostListView.as_view(), name='list'),
    path('view/<int:pk>/', cache_page(60)(BlogPostDetailView.as_view()), name='view'),
    path('edit/<int:pk>/', BlogPostUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', BlogPostDeleteView.as_view(), name='delete')
]

mailing_list_service/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('recipients/', include('recipients.urls', namespace='recipients')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

from users.models import User

NULLABLE = {'blank': True, 'null': True}


class BlogPost(models.Model):
    title = models.CharField(max_length=150, verbose_name='title')
    content = models.TextField(verbose_name='content')
    image = models.ImageField(upload_to='blog', verbose_name='image', **NULLABLE)
    views_count = models.IntegerField(default=0, verbose_name='views_count')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='created_at')
    author = models.ForeignKey(User, on_delete=models.SET_NULL, verbose_name='author', **NULLABLE)
    is_published = models.BooleanField(default=True, verbose_name='is_published')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'
        permissions = [
            ('can_unpublished', 'can unpublished')
        ]

blog/forms.py
from django import forms
from django.forms import BooleanField

from blog.models import BlogPost


class StyleFormMixin:
    """Стилизация формы"""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'


class BlogPostForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ('title', 'content', 'image')


class BlogPostModeratorForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ('is_published',)

blog/views.py
from django.core.exceptions import PermissionDenied
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView

from blog.forms import BlogPostForm, BlogPostModeratorForm
from blog.models import BlogPost
from blog.services import get_blog_posts_from_cash


class BlogPostCreateView(CreateView):
    model = BlogPost
    form_class = BlogPostForm
    success_url = reverse_lazy('blog:list')

    def form_valid(self, form):
        """Сохранение автора записи"""
        blog_post = form.save()
        user = self.request.user
        blog_post.author = user
        blog_post.save()
        return super().form_valid(form)


class BlogPostListView(ListView):
    model = BlogPost

    def get_queryset(self):
        """Вывод только активных записей, из кеша"""
        return get_blog_posts_from_cash()


class BlogPostDetailView(DetailView):
    model = BlogPost

    def get_object(self, queryset=None):
        """Увеличение количества просмотров"""
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class BlogPostUpdateView(UpdateView):
    model = BlogPost
    form_class = BlogPostForm
    success_url = reverse_lazy('blog:list')

    def get_success_url(self):
        """Перенаправление на просмотр записи после редактирования"""
        return reverse('blog:view', args=[self.kwargs.get('pk')])

    def get_form_class(self):
        """Переопределяем форму для модератора"""
        user = self.request.user
        if user == self.object.author:
            return BlogPostForm
        if user.has_perm('blog.can_unpublished'):
            return BlogPostModeratorForm
        raise PermissionDenied


class BlogPostDeleteView(DeleteView):
    model = BlogPost
    success_url = reverse_lazy('blog:list')

blog/templates/blog/blogpost_confirm_delete.html
{% extends 'mailing/base.html' %}
{% block content %}
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <p>Хотите удалить запись {{ object.title }}?</p>
                        <button type="submit" class="btn btn-success">Удалить</button>
                        <a class="btn btn-primary" href="{% url 'blog:list' %}" role="button">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/blogpost_detail.html
{% extends 'mailing/base.html' %}
{% load my_tags %}
{% block content %}
    <div class="container">
        <div class="row text-center">
            <div class="col-9">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">{{ object.title }}</h4>
                    </div>
                    <div class="card-body">
                        <h5>{{ object.content }}</h5>
                        <h5>От {{ object.created_at }}</h5>
                        {% if perms.blog.can_unpublished or user == object.author %}
                            <a class="btn btn-primary" href="{% url 'blog:edit' object.pk %}" role="button">Изменить</a>
                        {% endif %}
                        {% if user == object.author %}
                            <a class="btn btn-primary" href="{% url 'blog:delete' object.pk %}" role="button">Удалить</a>
                        {% endif %}
                        <a class="btn btn-primary" href="{% url 'blog:list' %}" role="button">Назад</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/blogpost_form.html
{% extends 'mailing/base.html' %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col">
                <form class="row" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="card">
                        <div class="card-body">
                            {{ form.as_p }}
                        </div>
                        <button type="submit" class="btn btn-primary mt-3">
                            {% if object %}
                                Изменить запись
                            {% else %}
                                Создать Запись
                            {% endif %}
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/blogpost_list.html
{% extends 'mailing/base.html' %}
{% load my_tags %}
{% block content %}
    <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
        <h1 class="display-4 fw-normal text-body-emphasis">Все записи</h1>
        {% if user.is_authenticated %}
            <h3>
                <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="{% url 'blog:create' %}">Создать запись</a>
            </h3>
        {% endif %}
    </div>
    <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
        {% for post in object_list %}
            <div class="col">
                <div class="card mb-4 rounded-3 shadow-sm">
                    <div class="card-header py-3">
                        <h2 class="my-0 fw-normal">{{ post.title }}</h2>
                    </div>
                    <div class="card-body">
                        <p class="card-title pricing-card-title">{{ post.content | slice:":100" }}</p>
                        {% if post.image %}
                          <img src="{{ post.image | media_filter }}" class="rounded mx-auto d-block w-100">
                        {% endif %}
                        <a class="btn btn-primary" href="{% url 'blog:view' post.pk %}" role="button">Просмотреть</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}