blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogPostCreateView, BlogPostListView, BlogPostDetailView, BlogPostUpdateView, BlogPostDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogPostCreateView.as_view(), name='create'),
    path('', BlogPostListView.as_view(), name='list'),
    path('view/<int:pk>/', cache_page(60)(BlogPostDetailView.as_view()), name='view'),
    path('edit/<int:pk>/', BlogPostUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', BlogPostDeleteView.as_view(), name='delete')
]

mailing_list_service/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('recipients/', include('recipients.urls', namespace='recipients')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import UserCreateView, email_verification, UserUpdateView, UserListView, change_activity

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('email-confirm/<str:token>', email_verification, name='email-confirm'),
    path('profile/', UserUpdateView.as_view(), name='profile'),
    path('users/', UserListView.as_view(), name='users_list'),
    path('activity/<int:pk>/', change_activity, name='activity'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField

NULLABLE = {'blank': True, 'null': True}


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='email')
    phone_number = PhoneNumberField(verbose_name='phone', **NULLABLE)
    avatar = models.ImageField(upload_to='users', verbose_name='avatar', **NULLABLE)
    token = models.CharField(max_length=100, verbose_name='token', **NULLABLE)
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'
        permissions = [
            ('can_see_users_list', 'can see all users'),
            ('can_deactivate_user', 'can deactivate user')
        ]

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms

from mailing.forms import StyleFormMixin
from users.models import User


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = User
        fields = ('email', 'phone_number', 'avatar')


class UserModeratorForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = User
        fields = ('email', 'is_active')

users/views.py
import secrets

from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.core.mail import send_mail
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView, ListView, DetailView

from users.forms import UserRegisterForm, UserForm, UserModeratorForm
from users.models import User
from mailing_list_service.settings import EMAIL_HOST_USER


class UserCreateView(CreateView):
    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        """Отправка письма для верификации почты"""
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(16)
        user.token = token
        user.save()
        host = self.request.get_host()
        url = f'http://{host}/users/email-confirm/{token}'
        send_mail(
            subject='Подтверждение почты',
            message=f'Для подтверждения почты перейдите по ссылке: {url}',
            from_email=EMAIL_HOST_USER,
            recipient_list=[user.email],
        )
        return super().form_valid(form)


def email_verification(request, token):
    """Подтверждение почты"""
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    return redirect(reverse('users:login'))


class UserUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserForm
    success_url = reverse_lazy('mailing:settings_list')

    def get_form_class(self):
        user = self.request.user
        if user.has_perm('users.can_deactivate_user'):
            return UserModeratorForm
        if user == self.request.user:
            return UserForm
        raise PermissionDenied

    def get_object(self, queryset=None):
        """Получаем текущего пользователя"""
        return self.request.user


class UserListView(LoginRequiredMixin, ListView):
    model = User


def change_activity(request, pk):
    """Изменение активности пользователя"""
    user = User.objects.get(pk=pk)
    if user.is_active:
        user.is_active = False
    else:
        user.is_active = True
    user.save()
    return redirect('users:users_list')

users/templates/users/login.html
{% extends 'mailing/base.html' %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col">
                <form class="row" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="card">
                        <div class="card-body">
                            {{ form.as_p }}
                        </div>
                        <button type="submit" class="btn btn-primary mt-3">Войти</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'mailing/base.html' %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col">
                <form class="row" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="card">
                        <div class="card-body">
                            {{ form.as_p }}
                        </div>
                        {% if object %}
                        <button type="submit" class="btn btn-primary mt-3">Сохранить изменения</button>
                        {% else %}
                        <button type="submit" class="btn btn-primary mt-3">Зарегистрироваться</button>
                        {% endif %}
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/user_list.html
{% extends 'mailing/base.html' %}

{% block content %}
    <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
        <h1 class="display-4 fw-normal text-body-emphasis">Все пользователи</h1>
    </div>
    {% if perms.users.can_see_users_list %}
        <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
            {% for user in object_list %}
                <div class="col">
                    <div class="card mb-4 rounded-3 shadow-sm">
                        <div class="card-header py-3">
                            <h2 class="my-0 fw-normal">{{ user.email }}</h2>
                        </div>
                        <div class="card-body">
                            <p class="card-title pricing-card-title">Телефон: {{ user.phone_number }}</p>
                            <p class="card-title pricing-card-title">Активность: {{ user.is_active }}</p>
                            {% if perms.users.can_deactivate_user and user.is_superuser == False %}
                                {% if user.is_active %}
                                    <a class="btn btn-primary" href="{% url 'users:activity' user.pk %}" role="button">Заблокировать</a>
                                {% else %}
                                    <a class="btn btn-primary" href="{% url 'users:activity' user.pk %}" role="button">Разблокировать</a>
                                {% endif %}
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% endif %}
{% endblock %}