blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogPostCreateView, BlogPostListView, BlogPostDetailView, BlogPostUpdateView, BlogPostDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogPostCreateView.as_view(), name='create'),
    path('', BlogPostListView.as_view(), name='list'),
    path('view/<int:pk>/', cache_page(60)(BlogPostDetailView.as_view()), name='view'),
    path('edit/<int:pk>/', BlogPostUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', BlogPostDeleteView.as_view(), name='delete')
]

mailing_list_service/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('recipients/', include('recipients.urls', namespace='recipients')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipients/urls.py
from django.urls import path

from recipients.apps import RecipientsConfig
from recipients.views import RecipientListView, RecipientCreateView, RecipientDetailView, RecipientDeleteView, \
    RecipientUpdateView

app_name = RecipientsConfig.name


urlpatterns = [
    path('', RecipientListView.as_view(), name='list'),
    path('create/', RecipientCreateView.as_view(), name='create'),
    path('<int:pk>/', RecipientDetailView.as_view(), name='view'),
    path('<int:pk>/update/', RecipientUpdateView.as_view(), name='edit'),
    path('<int:pk>/delete/', RecipientDeleteView.as_view(), name='delete'),
]

recipients/models.py
from django.db import models

from users.models import User


class Recipients(models.Model):
    """Модель получателей рассылки"""
    email = models.EmailField(verbose_name='email', unique=True)
    name = models.CharField(max_length=150, verbose_name='name')
    description = models.TextField(blank=True, null=True, verbose_name='description')

    def __str__(self):
        return self.email

    class Meta:
        verbose_name = 'Получатель'
        verbose_name_plural = 'Получатели'

recipients/forms.py
from django import forms

from recipients.models import Recipients


class StyleFormMixin:
    """Стилизация форм"""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class RecipientForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Recipients
        fields = '__all__'

recipients/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView, DeleteView, DetailView

from recipients.forms import RecipientForm
from recipients.models import Recipients


class RecipientCreateView(CreateView):
    model = Recipients
    form_class = RecipientForm
    success_url = reverse_lazy('recipients:list')


class RecipientListView(ListView):
    model = Recipients


class RecipientUpdateView(UpdateView):
    model = Recipients
    form_class = RecipientForm
    success_url = reverse_lazy('recipients:list')


class RecipientDeleteView(DeleteView):
    model = Recipients
    success_url = reverse_lazy('recipients:list')


class RecipientDetailView(DetailView):
    model = Recipients

recipients/templates/recipients/recipients_confirm_delete.html
{% extends 'mailing/base.html' %}
{% block content %}
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <p>Хотите удалить получателя {{ object.name }}?</p>
                        <button type="submit" class="btn btn-success">Удалить</button>
                        <a class="btn btn-primary" href="{% url 'recipients:list' %}" role="button">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

recipients/templates/recipients/recipients_detail.html
{% extends 'mailing/base.html' %}
{% block content %}
    <div class="container">
        <div class="row text-center">
            <div class="col-9">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h2 class="my-0 font-weight-normal">{{ object.name }}</h2>
                    </div>
                    <div class="card-body">
                        <h5>{{ object.description }}</h5>
                        <p>Почта: {{ object.email }}</p>
                        {% if user.is_superuser %}
                        <a class="btn btn-primary" href="{% url 'recipients:edit' object.pk %}" role="button">Изменить</a>
                        <a class="btn btn-primary" href="{% url 'recipients:delete' object.pk %}" role="button">Удалить</a>
                        {% endif %}
                        <a class="btn btn-primary" href="{% url 'recipients:list' %}" role="button">Назад</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

recipients/templates/recipients/recipients_form.html
{% extends 'mailing/base.html' %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col">
                <form class="row" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="card">
                        <div class="card-body">
                            {{ form.as_p }}
                        </div>
                        <button type="submit" class="btn btn-primary mt-3">
                            {% if object %}
                                Изменить получателя
                            {% else %}
                                Добавить получателя
                            {% endif %}
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

recipients/templates/recipients/recipients_list.html
{% extends 'mailing/base.html' %}
{% block content %}
    <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
        <h1 class="display-4 fw-normal text-body-emphasis">Все получатели</h1>
        {% if user.is_authenticated %}
            <h3>
              <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="{% url 'recipients:create' %}">Добавить получателя</a>
            </h3>
        {% endif %}
    </div>
    <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
        {% for recipients in object_list %}
            <div class="col">
                <div class="card mb-4 rounded-3 shadow-sm">
                    <div class="card-header py-3">
                        <h2 class="my-0 fw-normal">{{ recipients.name }}</h2>
                    </div>
                    <div class="card-body">
                        <h4 class="card-title pricing-card-title">{{ recipients.description | slice:":100" }}</h4>
                        <p>Почта: {{ recipients.email }}</p>
                        <a class="btn btn-primary" href="{% url 'recipients:view' recipients.pk %}" role="button">Просмотреть</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}